[project]
name = "mcp-twitch"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "fastmcp>=2.12.3",
    "httpx>=0.28.1",
    "python-dotenv>=1.1.1",
]
