[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "ON_FAILURE" 
restartPolicyMaxRetries = 10

[env]
FASTMCP_LOG_LEVEL = "INFO"
PORT = "8080"
HOST = "0.0.0.0"
TRANSPORT = "http"
